homepage: https://github.com/tomas-ingram/dart-ctags
description: ctags compatible tag file generator for dart code
name: dart_ctags
version: 2.12.0
environment:
    sdk: ">=2.12.0 <3.0.0"
executables:
    dart_ctags: tags
dependencies:
    analyzer: ^2.7.0
    path: ^1.7.0
    quiver: ^3.0.1
    args: ^2.3.0
dev_dependencies:
    pedantic: ^1.9.2
